import { createClient } from '@supabase/supabase-js';
import { Database } from '@/lib/types/database';

// Initialize the Supabase client with environment variables
const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const supabaseAnonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);

// Type definition for database (would be generated by Supabase CLI in a real project)
export type Database = {
  public: {
    Tables: {
      events_raw: {
        Row: {
          id: string;
          created_at: string;
          user_id: string;
          events: any; // JSONB in Supabase
        };
        Insert: {
          id?: string;
          created_at?: string;
          user_id: string;
          events: any;
        };
      };
      summaries: {
        Row: {
          id: string;
          created_at: string;
          user_id: string;
          event_id: string;
          cluster_label: string;
          root_cause: string;
          sample: string[];
          severity: string;
          count: number;
        };
        Insert: {
          id?: string;
          created_at?: string;
          user_id: string;
          event_id: string;
          cluster_label: string;
          root_cause: string;
          sample: string[];
          severity: string;
          count: number;
        };
      };
    };
  };
};